### ISSUE TITLE
Should these actually be unsigned ints?! 😱

### ISSUE THREAD

**Issue by gabriellet** [gabriellet/chip8-emulator#1]
I'm wondering if some of the fixed size registers, and other things should actually be unsigned ints rather than signed ints.

```
int16_t PC = 0;                     //Program counter
int8_t SP = 0;                      //Stack Pointer
int16_t stack[16] = {0};            //Stack
```
Example, that stack pointer. And when would we need to use them, versus when do we not?

**Comment by DavidWatkins** [comment]
I think those should all be unsigned integers. I can't imagine a situation where any of those are negative.

**Comment by gabriellet** [comment]
So those, the delay and sound timers, and the address register should all be unsigned then? (I take it only the general purpose ones should be signed; we should be able to store negative values.)

**Comment by DavidWatkins** [comment]
Yeah. Anything that logically should be signed should be, timers, delays, and pointers aren't signed usually.

**Comment by gabriellet** [comment]
I'm glad I caught this before it caused some weird errors.
